# Generated by Django 4.0.3 on 2023-07-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
