# Generated by Django 4.0.3 on 2023-08-09 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_question_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='user',
        ),
        migrations.AddField(
            model_name='response',
            name='cookie_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
