# Generated by Django 4.0.3 on 2023-09-07 23:23

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_response_user_response_cookie_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='email_answer',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='question_files/'),
        ),
        migrations.AddField(
            model_name='answer',
            name='phone_answer',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?\\d{1,15}$')]),
        ),
        migrations.AddField(
            model_name='answer',
            name='small_text',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='response',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='response',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('abandoned', 'Abandoned')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('open_ended', 'Open Ended'), ('file', 'File'), ('email', 'Email'), ('phone', 'Phone'), ('text', 'Text')], max_length=20),
        ),
    ]
