# Generated by Django 4.0.3 on 2023-09-08 08:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_answer_email_answer_answer_file_upload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='last_edited',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
