# Generated by Django 4.0.3 on 2023-09-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_response_last_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
