# Generated by Django 4.0.3 on 2023-09-15 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_questioncategory_question_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='completion_mail_sent',
            field=models.BooleanField(default=False),
        ),
    ]
