# Generated by Django 4.0.3 on 2023-09-15 05:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_response_completion_mail_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='weight',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Value must be greater than or equal to 0'), django.core.validators.MaxValueValidator(100, message='Value must be less than or equal to 100')]),
        ),
    ]
