# Generated by Django 4.0.3 on 2023-09-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_question_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='outro_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='outro_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
