# Generated by Django 4.0.3 on 2023-09-28 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_option_goto'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='skipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('multiple_choice', 'multiple_choice'), ('open_ended', 'open_ended'), ('file', 'file'), ('email', 'email'), ('phone', 'phone'), ('text', 'text')], max_length=20),
        ),
    ]
