# Generated by Django 4.0.3 on 2023-10-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_answer_skipped_alter_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
