# Generated by Django 4.0.3 on 2023-10-22 15:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_question_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='weight',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Value must be greater than or equal to 0'), django.core.validators.MaxValueValidator(100, message='Value must be less than or equal to 100')]),
        ),
        migrations.AddField(
            model_name='questioncategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('multiple_choice', 'multiple_choice'), ('multiple_select', 'multiple_select'), ('open_ended', 'open_ended'), ('file', 'file'), ('email', 'email'), ('phone', 'phone'), ('text', 'text')], max_length=20),
        ),
    ]
