# Generated by Django 4.0.3 on 2023-10-23 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_option_weight_questioncategory_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='options',
            field=models.ManyToManyField(blank=True, related_name='options', to='api.option'),
        ),
    ]
