# Generated by Django 4.0.3 on 2023-11-10 02:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_answer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='weight',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0, message='Value must be greater than or equal to 0.0'), django.core.validators.MaxValueValidator(100.0, message='Value must be less than or equal to 100.0')]),
        ),
        migrations.AlterField(
            model_name='question',
            name='weight',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0, message='Value must be greater than or equal to 0.0'), django.core.validators.MaxValueValidator(100.0, message='Value must be less than or equal to 100.0')]),
        ),
    ]
