# Generated by Django 4.0.3 on 2023-11-13 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_response_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='old_cookie_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
